### ISSUE TITLE
How to manually update MC after using this script?

### ISSUE THREAD

**Issue by ghost** [techahold/Meshcentral-Installer#2]
The built-in server updater doesn't work after installing using this script (it kills the install). meshcentral-data folders etc aren't installed in the "correct" location (user home folder) so simply running `npm install meshcentral` doesn't work from user prompt. 

How to manually update the server after installing with this script?

**Comment by dinger1986** [comment]
I know the update on mesh itself is a little ropey right now but can check it, it should be fine where it's installed and is the "correct" location as far as linux is concerned (maybe not NPM 😜)

**Comment by ghost** [comment]
The install location is /opt/meshcentral/ folder. I tried running `npm install meshcentral` in that folder and it killed the install (again!)

Currently my server is sitting on 1.1.9 with the latest 1.1.11 and unable to update :(

**Comment by dinger1986** [comment]
no worries, Ill take a look at it

**Comment by ghost** [comment]
Any update on this @dinger1986 ?

**Comment by dinger1986** [comment]
no, I dont use mesh anymore so need to spin up a server etc to look at it and figure out whats wrong, its on my list

**Comment by ghost** [comment]
Update yet on this issue?

**Comment by dinger1986** [comment]
No, I might just archive this, long list not got loads of time and don't need getting chased as again I don't use meshcentral
